name: Pull request validation

on: pull_request

jobs:

  test-publish:
    name: Try npm publishing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node 11
      uses: actions/setup-node@v1
      with:
        node-version: 11.x

    - run: npm install
      working-directory: importer

    - run: npm install
      working-directory: packages/svg-icons

    - run: |
        npm config set //registry.npmjs.org:_authToken ${NODE_AUTH_TOKEN}
        npm publish --ignore-scripts --dry-run
      working-directory: packages/svg-icons
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
